syntax = "proto3";

// 定义包名
package payment;
option go_package = "./enum/payment";


// 支付
enum Payment {
  Payment_UNKNOWN = 0;
  // 支付宝
  Alipay = 1;
  // 微信
  Wxpay = 2;
}

enum PaymentProduct {
  PaymentMethod_UNKNOWN = 0;
  // H5
  H5 = 1;
  // APP
  APP = 2;
  // JSAPI
  JSAPI = 3;
  // 人脸支付
  Face = 4;
  // 扫码
  Qrcode = 5;
  // 设备扫码
  Scan = 6;
  // 小程序
  LITE = 7;
  // 先享后付
  AFTER_PAY = 8;
  // 免押金付款使用
  DEPOSIT_PAY = 9;
}

enum Currency {
  Currency_UNKNOWN = 0;
  CNY = 1;
  USD = 2;
}

enum Status {
  Status_UNKNOWN = 0;
  // 预支付,创建支付订单后的状态，等待用户完成支付
  Pending = 1;
  // 成功
  Success = 2;
  // 失败
  Failed = 3;
  // 取消, 付款码用户取消支付，或者其他主动取消支付
  Cancel = 4;
  // 关闭，超时关闭等其他关闭
  Close = 5;
  // 退款
  Refund = 6;
  // WAIT_CONFIRM
  WaitConfirm = 7;
  // WAIT_PAY
  WaitPay = 8;
}