// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: enum/payment/payment.proto

// 定义包名

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付
type Payment int32

const (
	Payment_Payment_UNKNOWN Payment = 0
	// 支付宝
	Payment_Alipay Payment = 1
	// 微信
	Payment_Wxpay Payment = 2
)

// Enum value maps for Payment.
var (
	Payment_name = map[int32]string{
		0: "Payment_UNKNOWN",
		1: "Alipay",
		2: "Wxpay",
	}
	Payment_value = map[string]int32{
		"Payment_UNKNOWN": 0,
		"Alipay":          1,
		"Wxpay":           2,
	}
)

func (x Payment) Enum() *Payment {
	p := new(Payment)
	*p = x
	return p
}

func (x Payment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Payment) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_payment_payment_proto_enumTypes[0].Descriptor()
}

func (Payment) Type() protoreflect.EnumType {
	return &file_enum_payment_payment_proto_enumTypes[0]
}

func (x Payment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Payment.Descriptor instead.
func (Payment) EnumDescriptor() ([]byte, []int) {
	return file_enum_payment_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentProduct int32

const (
	PaymentProduct_PaymentMethod_UNKNOWN PaymentProduct = 0
	// H5
	PaymentProduct_H5 PaymentProduct = 1
	// APP
	PaymentProduct_APP PaymentProduct = 2
	// JSAPI
	PaymentProduct_JSAPI PaymentProduct = 3
	// 原生支付
	PaymentProduct_Native PaymentProduct = 4
	// 人脸支付
	PaymentProduct_Face PaymentProduct = 5
	// 扫码
	PaymentProduct_Qrcode PaymentProduct = 6
	// 设备扫码
	PaymentProduct_Scan PaymentProduct = 7
	// 小程序
	PaymentProduct_LITE PaymentProduct = 8
	// 先享后付
	PaymentProduct_AFTER_PAY PaymentProduct = 9
	// 免押金付款使用
	PaymentProduct_DEPOSIT_PAY PaymentProduct = 10
)

// Enum value maps for PaymentProduct.
var (
	PaymentProduct_name = map[int32]string{
		0:  "PaymentMethod_UNKNOWN",
		1:  "H5",
		2:  "APP",
		3:  "JSAPI",
		4:  "Native",
		5:  "Face",
		6:  "Qrcode",
		7:  "Scan",
		8:  "LITE",
		9:  "AFTER_PAY",
		10: "DEPOSIT_PAY",
	}
	PaymentProduct_value = map[string]int32{
		"PaymentMethod_UNKNOWN": 0,
		"H5":                    1,
		"APP":                   2,
		"JSAPI":                 3,
		"Native":                4,
		"Face":                  5,
		"Qrcode":                6,
		"Scan":                  7,
		"LITE":                  8,
		"AFTER_PAY":             9,
		"DEPOSIT_PAY":           10,
	}
)

func (x PaymentProduct) Enum() *PaymentProduct {
	p := new(PaymentProduct)
	*p = x
	return p
}

func (x PaymentProduct) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentProduct) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_payment_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentProduct) Type() protoreflect.EnumType {
	return &file_enum_payment_payment_proto_enumTypes[1]
}

func (x PaymentProduct) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentProduct.Descriptor instead.
func (PaymentProduct) EnumDescriptor() ([]byte, []int) {
	return file_enum_payment_payment_proto_rawDescGZIP(), []int{1}
}

type Currency int32

const (
	Currency_Currency_UNKNOWN Currency = 0
	Currency_CNY              Currency = 1
	Currency_USD              Currency = 2
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "Currency_UNKNOWN",
		1: "CNY",
		2: "USD",
	}
	Currency_value = map[string]int32{
		"Currency_UNKNOWN": 0,
		"CNY":              1,
		"USD":              2,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_payment_payment_proto_enumTypes[2].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_enum_payment_payment_proto_enumTypes[2]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_enum_payment_payment_proto_rawDescGZIP(), []int{2}
}

type Status int32

const (
	Status_Status_UNKNOWN Status = 0
	// 预支付,创建支付订单后的状态，等待用户完成支付
	Status_Pending Status = 1
	// 成功
	Status_Success Status = 2
	// 失败
	Status_Failed Status = 3
	// 取消, 付款码用户取消支付，或者其他主动取消支付
	Status_Cancel Status = 4
	// 关闭，超时关闭等其他关闭
	Status_Close Status = 5
	// 退款
	Status_Refund Status = 6
	// WAIT_CONFIRM
	Status_WaitConfirm Status = 7
	// WAIT_PAY
	Status_WaitPay Status = 8
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Status_UNKNOWN",
		1: "Pending",
		2: "Success",
		3: "Failed",
		4: "Cancel",
		5: "Close",
		6: "Refund",
		7: "WaitConfirm",
		8: "WaitPay",
	}
	Status_value = map[string]int32{
		"Status_UNKNOWN": 0,
		"Pending":        1,
		"Success":        2,
		"Failed":         3,
		"Cancel":         4,
		"Close":          5,
		"Refund":         6,
		"WaitConfirm":    7,
		"WaitPay":        8,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_payment_payment_proto_enumTypes[3].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_enum_payment_payment_proto_enumTypes[3]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_enum_payment_payment_proto_rawDescGZIP(), []int{3}
}

var File_enum_payment_payment_proto protoreflect.FileDescriptor

var file_enum_payment_payment_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2a, 0x35, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x13, 0x0a, 0x0f, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x78, 0x70, 0x61, 0x79, 0x10, 0x02, 0x2a, 0x9d, 0x01, 0x0a,
	0x0e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12,
	0x19, 0x0a, 0x15, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x48, 0x35,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x50, 0x50, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4a,
	0x53, 0x41, 0x50, 0x49, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65,
	0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x61, 0x63, 0x65, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06,
	0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e,
	0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49, 0x54, 0x45, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09,
	0x41, 0x46, 0x54, 0x45, 0x52, 0x5f, 0x50, 0x41, 0x59, 0x10, 0x09, 0x12, 0x0f, 0x0a, 0x0b, 0x44,
	0x45, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x5f, 0x50, 0x41, 0x59, 0x10, 0x0a, 0x2a, 0x32, 0x0a, 0x08,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x43, 0x4e, 0x59, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x53, 0x44, 0x10, 0x02,
	0x2a, 0x83, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x10,
	0x04, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x61, 0x69, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x61, 0x69,
	0x74, 0x50, 0x61, 0x79, 0x10, 0x08, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x65, 0x6e, 0x75, 0x6d,
	0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_payment_payment_proto_rawDescOnce sync.Once
	file_enum_payment_payment_proto_rawDescData = file_enum_payment_payment_proto_rawDesc
)

func file_enum_payment_payment_proto_rawDescGZIP() []byte {
	file_enum_payment_payment_proto_rawDescOnce.Do(func() {
		file_enum_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_payment_payment_proto_rawDescData)
	})
	return file_enum_payment_payment_proto_rawDescData
}

var file_enum_payment_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_enum_payment_payment_proto_goTypes = []interface{}{
	(Payment)(0),        // 0: payment.Payment
	(PaymentProduct)(0), // 1: payment.PaymentProduct
	(Currency)(0),       // 2: payment.Currency
	(Status)(0),         // 3: payment.Status
}
var file_enum_payment_payment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_payment_payment_proto_init() }
func file_enum_payment_payment_proto_init() {
	if File_enum_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_payment_payment_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_payment_payment_proto_goTypes,
		DependencyIndexes: file_enum_payment_payment_proto_depIdxs,
		EnumInfos:         file_enum_payment_payment_proto_enumTypes,
	}.Build()
	File_enum_payment_payment_proto = out.File
	file_enum_payment_payment_proto_rawDesc = nil
	file_enum_payment_payment_proto_goTypes = nil
	file_enum_payment_payment_proto_depIdxs = nil
}
