// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: enum/payment/payment.proto

// 定义包名

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付
type Payment int32

const (
	Payment_Payment_UNKNOWN Payment = 0
	// 支付宝
	Payment_Alipay Payment = 1
	// 微信
	Payment_Wxpay Payment = 2
)

// Enum value maps for Payment.
var (
	Payment_name = map[int32]string{
		0: "Payment_UNKNOWN",
		1: "Alipay",
		2: "Wxpay",
	}
	Payment_value = map[string]int32{
		"Payment_UNKNOWN": 0,
		"Alipay":          1,
		"Wxpay":           2,
	}
)

func (x Payment) Enum() *Payment {
	p := new(Payment)
	*p = x
	return p
}

func (x Payment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Payment) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_payment_payment_proto_enumTypes[0].Descriptor()
}

func (Payment) Type() protoreflect.EnumType {
	return &file_enum_payment_payment_proto_enumTypes[0]
}

func (x Payment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Payment.Descriptor instead.
func (Payment) EnumDescriptor() ([]byte, []int) {
	return file_enum_payment_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentProduct int32

const (
	PaymentProduct_PaymentMethod_UNKNOWN PaymentProduct = 0
	// H5
	PaymentProduct_H5 PaymentProduct = 1
	// APP
	PaymentProduct_APP PaymentProduct = 2
	// JSAPI
	PaymentProduct_JSAPI PaymentProduct = 3
	// 人脸支付
	PaymentProduct_Face PaymentProduct = 4
	// 扫码
	PaymentProduct_Qrcode PaymentProduct = 5
	// 设备扫码
	PaymentProduct_Scan PaymentProduct = 6
	// 小程序
	PaymentProduct_LITE PaymentProduct = 7
	// 先享后付
	PaymentProduct_AFTER_PAY PaymentProduct = 8
	// 免押金付款使用
	PaymentProduct_DEPOSIT_PAY PaymentProduct = 9
	// PC, PC端
	PaymentProduct_PC PaymentProduct = 10
)

// Enum value maps for PaymentProduct.
var (
	PaymentProduct_name = map[int32]string{
		0:  "PaymentMethod_UNKNOWN",
		1:  "H5",
		2:  "APP",
		3:  "JSAPI",
		4:  "Face",
		5:  "Qrcode",
		6:  "Scan",
		7:  "LITE",
		8:  "AFTER_PAY",
		9:  "DEPOSIT_PAY",
		10: "PC",
	}
	PaymentProduct_value = map[string]int32{
		"PaymentMethod_UNKNOWN": 0,
		"H5":                    1,
		"APP":                   2,
		"JSAPI":                 3,
		"Face":                  4,
		"Qrcode":                5,
		"Scan":                  6,
		"LITE":                  7,
		"AFTER_PAY":             8,
		"DEPOSIT_PAY":           9,
		"PC":                    10,
	}
)

func (x PaymentProduct) Enum() *PaymentProduct {
	p := new(PaymentProduct)
	*p = x
	return p
}

func (x PaymentProduct) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentProduct) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_payment_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentProduct) Type() protoreflect.EnumType {
	return &file_enum_payment_payment_proto_enumTypes[1]
}

func (x PaymentProduct) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentProduct.Descriptor instead.
func (PaymentProduct) EnumDescriptor() ([]byte, []int) {
	return file_enum_payment_payment_proto_rawDescGZIP(), []int{1}
}

type Currency int32

const (
	Currency_Currency_UNKNOWN Currency = 0
	Currency_CNY              Currency = 1
	Currency_USD              Currency = 2
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "Currency_UNKNOWN",
		1: "CNY",
		2: "USD",
	}
	Currency_value = map[string]int32{
		"Currency_UNKNOWN": 0,
		"CNY":              1,
		"USD":              2,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_payment_payment_proto_enumTypes[2].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_enum_payment_payment_proto_enumTypes[2]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_enum_payment_payment_proto_rawDescGZIP(), []int{2}
}

type Status int32

const (
	Status_Status_UNKNOWN Status = 0
	// 预支付,创建支付订单后的状态，等待用户完成支付
	Status_Pending Status = 1
	// 成功
	Status_Success Status = 2
	// 失败
	Status_Failed Status = 3
	// 取消, 付款码用户取消支付，或者其他主动取消支付
	Status_Cancel Status = 4
	// 关闭，超时关闭等其他关闭
	Status_Close Status = 5
	// 退款
	Status_Refund Status = 6
	// WAIT_CONFIRM
	Status_WaitConfirm Status = 7
	// WAIT_PAY
	Status_WaitPay Status = 8
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Status_UNKNOWN",
		1: "Pending",
		2: "Success",
		3: "Failed",
		4: "Cancel",
		5: "Close",
		6: "Refund",
		7: "WaitConfirm",
		8: "WaitPay",
	}
	Status_value = map[string]int32{
		"Status_UNKNOWN": 0,
		"Pending":        1,
		"Success":        2,
		"Failed":         3,
		"Cancel":         4,
		"Close":          5,
		"Refund":         6,
		"WaitConfirm":    7,
		"WaitPay":        8,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_payment_payment_proto_enumTypes[3].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_enum_payment_payment_proto_enumTypes[3]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_enum_payment_payment_proto_rawDescGZIP(), []int{3}
}

var File_enum_payment_payment_proto protoreflect.FileDescriptor

const file_enum_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1aenum/payment/payment.proto\x12\apayment*5\n" +
	"\aPayment\x12\x13\n" +
	"\x0fPayment_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06Alipay\x10\x01\x12\t\n" +
	"\x05Wxpay\x10\x02*\x99\x01\n" +
	"\x0ePaymentProduct\x12\x19\n" +
	"\x15PaymentMethod_UNKNOWN\x10\x00\x12\x06\n" +
	"\x02H5\x10\x01\x12\a\n" +
	"\x03APP\x10\x02\x12\t\n" +
	"\x05JSAPI\x10\x03\x12\b\n" +
	"\x04Face\x10\x04\x12\n" +
	"\n" +
	"\x06Qrcode\x10\x05\x12\b\n" +
	"\x04Scan\x10\x06\x12\b\n" +
	"\x04LITE\x10\a\x12\r\n" +
	"\tAFTER_PAY\x10\b\x12\x0f\n" +
	"\vDEPOSIT_PAY\x10\t\x12\x06\n" +
	"\x02PC\x10\n" +
	"*2\n" +
	"\bCurrency\x12\x14\n" +
	"\x10Currency_UNKNOWN\x10\x00\x12\a\n" +
	"\x03CNY\x10\x01\x12\a\n" +
	"\x03USD\x10\x02*\x83\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x0eStatus_UNKNOWN\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\v\n" +
	"\aSuccess\x10\x02\x12\n" +
	"\n" +
	"\x06Failed\x10\x03\x12\n" +
	"\n" +
	"\x06Cancel\x10\x04\x12\t\n" +
	"\x05Close\x10\x05\x12\n" +
	"\n" +
	"\x06Refund\x10\x06\x12\x0f\n" +
	"\vWaitConfirm\x10\a\x12\v\n" +
	"\aWaitPay\x10\bB\x10Z\x0e./enum/paymentb\x06proto3"

var (
	file_enum_payment_payment_proto_rawDescOnce sync.Once
	file_enum_payment_payment_proto_rawDescData []byte
)

func file_enum_payment_payment_proto_rawDescGZIP() []byte {
	file_enum_payment_payment_proto_rawDescOnce.Do(func() {
		file_enum_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_payment_payment_proto_rawDesc), len(file_enum_payment_payment_proto_rawDesc)))
	})
	return file_enum_payment_payment_proto_rawDescData
}

var file_enum_payment_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_enum_payment_payment_proto_goTypes = []any{
	(Payment)(0),        // 0: payment.Payment
	(PaymentProduct)(0), // 1: payment.PaymentProduct
	(Currency)(0),       // 2: payment.Currency
	(Status)(0),         // 3: payment.Status
}
var file_enum_payment_payment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_payment_payment_proto_init() }
func file_enum_payment_payment_proto_init() {
	if File_enum_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_payment_payment_proto_rawDesc), len(file_enum_payment_payment_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_payment_payment_proto_goTypes,
		DependencyIndexes: file_enum_payment_payment_proto_depIdxs,
		EnumInfos:         file_enum_payment_payment_proto_enumTypes,
	}.Build()
	File_enum_payment_payment_proto = out.File
	file_enum_payment_payment_proto_goTypes = nil
	file_enum_payment_payment_proto_depIdxs = nil
}
