package driver

import "github.com/lihongsheng/payment-sdk/config/params"

var options = &params.Option{
	Label:        "微信配置项",
	Name:         "",
	Type:         params.Object,
	ValidateReg:  "",
	ValidateType: "",
	InputType:    "",
	Default:      "",
	Values:       nil,
	// 嵌套的Config字段配置
	Properties: []params.Option{
		{
			Label:        "微信AppID",
			Name:         "app_id",
			Type:         "String",
			ValidateReg:  "^wx[0-9a-zA-Z]{16,32}$",
			ValidateType: params.ValidateReg,
			InputType:    params.InputText,
			Default:      "",
			Values:       nil,
			Properties:   nil,
			Require:      true,
		},
		{
			Label:        "微信商户ID",
			Name:         "mch_id",
			Type:         "String",
			ValidateReg:  "^[0-9]{10,15}$",
			ValidateType: "Reg",
			InputType:    "text",
			Default:      "",
			Values:       nil,
			Properties:   nil,
			Require:      true,
		},
		{
			Label:        "微信API V3秘钥",
			Name:         "api_secret",
			Type:         "String",
			ValidateReg:  "^[0-9a-zA-Z]{32,64}$",
			ValidateType: params.ValidateReg,
			InputType:    params.InputPassword,
			Default:      "",
			Values:       nil,
			Properties:   nil,
			Require:      true,
		},
		// 证书信息（嵌套Object）
		{
			Label:        "证书信息",
			Name:         "cert",
			Type:         "Object",
			ValidateReg:  "",
			ValidateType: "",
			InputType:    "",
			Default:      "",
			Values:       nil,
			Require:      true,
			Properties: []params.Option{
				{
					Label:        "应用私钥",
					Name:         "private_key",
					Type:         params.String,
					ValidateReg:  "",
					ValidateType: params.ValidateRsaPrivate,
					InputType:    params.InputTextarea,
					Default:      "",
					Values:       nil,
					Properties:   nil,
					Require:      true,
				},
				{
					Label:        "私钥证书序列号",
					Name:         "private_number",
					Type:         params.String,
					ValidateReg:  "",
					ValidateType: params.ValidateString,
					InputType:    params.InputText,
					Default:      "",
					Values:       nil,
					Properties:   nil,
					Require:      true,
				},
				{
					Label:        "微信公钥证书序列号",
					Name:         "public_number",
					Type:         params.String,
					ValidateReg:  "",
					ValidateType: params.ValidateString,
					InputType:    params.InputText,
					Default:      "",
					Values:       nil,
					Properties:   nil,
					Require:      true,
				},
				{
					Label:        "微信公钥",
					Name:         "public",
					Type:         params.String,
					ValidateReg:  "",
					ValidateType: params.ValidateRsaPublic,
					InputType:    params.InputTextarea,
					Default:      "",
					Values:       nil,
					Properties:   nil,
					Require:      true,
				},
			},
		},

		{
			Label:        "应用Secret",
			Name:         "app_secret",
			Type:         "String",
			ValidateReg:  "",
			ValidateType: params.ValidateString,
			InputType:    params.InputPassword,
			Default:      "",
			Values:       nil,
			Properties:   nil,
			Require:      true,
		},
	},
}
