// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: enum/channel/channel.proto

// 定义包名

package channel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel int32

const (
	Channel_Channel_UNKNOWN Channel = 0
	// 支付宝
	Channel_Alipay Channel = 1
	// 微信
	Channel_Wxpay Channel = 2
	// 富有
	Channel_Fuiou Channel = 3
	// 拉卡拉
	Channel_Lakala Channel = 4
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "Channel_UNKNOWN",
		1: "Alipay",
		2: "Wxpay",
		3: "Fuiou",
		4: "Lakala",
	}
	Channel_value = map[string]int32{
		"Channel_UNKNOWN": 0,
		"Alipay":          1,
		"Wxpay":           2,
		"Fuiou":           3,
		"Lakala":          4,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_channel_channel_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_enum_channel_channel_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_enum_channel_channel_proto_rawDescGZIP(), []int{0}
}

var File_enum_channel_channel_proto protoreflect.FileDescriptor

const file_enum_channel_channel_proto_rawDesc = "" +
	"\n" +
	"\x1aenum/channel/channel.proto\x12\achannel*L\n" +
	"\aChannel\x12\x13\n" +
	"\x0fChannel_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06Alipay\x10\x01\x12\t\n" +
	"\x05Wxpay\x10\x02\x12\t\n" +
	"\x05Fuiou\x10\x03\x12\n" +
	"\n" +
	"\x06Lakala\x10\x04B\x10Z\x0e./enum/channelb\x06proto3"

var (
	file_enum_channel_channel_proto_rawDescOnce sync.Once
	file_enum_channel_channel_proto_rawDescData []byte
)

func file_enum_channel_channel_proto_rawDescGZIP() []byte {
	file_enum_channel_channel_proto_rawDescOnce.Do(func() {
		file_enum_channel_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_channel_channel_proto_rawDesc), len(file_enum_channel_channel_proto_rawDesc)))
	})
	return file_enum_channel_channel_proto_rawDescData
}

var file_enum_channel_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_channel_channel_proto_goTypes = []any{
	(Channel)(0), // 0: channel.Channel
}
var file_enum_channel_channel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_channel_channel_proto_init() }
func file_enum_channel_channel_proto_init() {
	if File_enum_channel_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_channel_channel_proto_rawDesc), len(file_enum_channel_channel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_channel_channel_proto_goTypes,
		DependencyIndexes: file_enum_channel_channel_proto_depIdxs,
		EnumInfos:         file_enum_channel_channel_proto_enumTypes,
	}.Build()
	File_enum_channel_channel_proto = out.File
	file_enum_channel_channel_proto_goTypes = nil
	file_enum_channel_channel_proto_depIdxs = nil
}
