// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: enum/channel/channel.proto

// 定义包名

package channel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel int32

const (
	Channel_Channel_UNKNOWN Channel = 0
	// 支付宝
	Channel_Alipay Channel = 1
	// 微信
	Channel_Wxpay Channel = 2
	// 富有
	Channel_Fuiou Channel = 3
	//  拉卡拉正常版
	Channel_Lakala_NORMAL Channel = 4
	// 拉卡拉-缴费易
	Channel_Lakala_JFYUI Channel = 5
	// 易云汇
	Channel_YUNHUI Channel = 6
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "Channel_UNKNOWN",
		1: "Alipay",
		2: "Wxpay",
		3: "Fuiou",
		4: "Lakala_NORMAL",
		5: "Lakala_JFYUI",
		6: "YUNHUI",
	}
	Channel_value = map[string]int32{
		"Channel_UNKNOWN": 0,
		"Alipay":          1,
		"Wxpay":           2,
		"Fuiou":           3,
		"Lakala_NORMAL":   4,
		"Lakala_JFYUI":    5,
		"YUNHUI":          6,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_channel_channel_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_enum_channel_channel_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_enum_channel_channel_proto_rawDescGZIP(), []int{0}
}

var File_enum_channel_channel_proto protoreflect.FileDescriptor

var file_enum_channel_channel_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2a, 0x71, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x13, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x6c, 0x69, 0x70, 0x61, 0x79, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x78, 0x70, 0x61, 0x79, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05,
	0x46, 0x75, 0x69, 0x6f, 0x75, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x61, 0x6b, 0x61, 0x6c,
	0x61, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x61,
	0x6b, 0x61, 0x6c, 0x61, 0x5f, 0x4a, 0x46, 0x59, 0x55, 0x49, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06,
	0x59, 0x55, 0x4e, 0x48, 0x55, 0x49, 0x10, 0x06, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_enum_channel_channel_proto_rawDescOnce sync.Once
	file_enum_channel_channel_proto_rawDescData = file_enum_channel_channel_proto_rawDesc
)

func file_enum_channel_channel_proto_rawDescGZIP() []byte {
	file_enum_channel_channel_proto_rawDescOnce.Do(func() {
		file_enum_channel_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_channel_channel_proto_rawDescData)
	})
	return file_enum_channel_channel_proto_rawDescData
}

var file_enum_channel_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_channel_channel_proto_goTypes = []interface{}{
	(Channel)(0), // 0: channel.Channel
}
var file_enum_channel_channel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_channel_channel_proto_init() }
func file_enum_channel_channel_proto_init() {
	if File_enum_channel_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_channel_channel_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_channel_channel_proto_goTypes,
		DependencyIndexes: file_enum_channel_channel_proto_depIdxs,
		EnumInfos:         file_enum_channel_channel_proto_enumTypes,
	}.Build()
	File_enum_channel_channel_proto = out.File
	file_enum_channel_channel_proto_rawDesc = nil
	file_enum_channel_channel_proto_goTypes = nil
	file_enum_channel_channel_proto_depIdxs = nil
}
