// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: enum/refund/refund.proto

// 定义包名

package refund

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Status_UNKNOWN Status = 0
	// 初始化
	Status_Created Status = 1
	// 预支付,创建支付订单后的状态，等待用户完成支付
	Status_Pending Status = 2
	// 成功
	Status_Success Status = 3
	// 失败
	Status_Failed Status = 4
	// 异常
	Status_Abnormal Status = 5
	Status_Closed   Status = 6
	Status_Cancel   Status = 7
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Status_UNKNOWN",
		1: "Created",
		2: "Pending",
		3: "Success",
		4: "Failed",
		5: "Abnormal",
		6: "Closed",
		7: "Cancel",
	}
	Status_value = map[string]int32{
		"Status_UNKNOWN": 0,
		"Created":        1,
		"Pending":        2,
		"Success":        3,
		"Failed":         4,
		"Abnormal":       5,
		"Closed":         6,
		"Cancel":         7,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_refund_refund_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_enum_refund_refund_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_enum_refund_refund_proto_rawDescGZIP(), []int{0}
}

// ORIGINAL: 原路退款
//
//BALANCE: 退回到余额
//
//OTHER_BALANCE: 原账户异常退到其他余额账户
//
//OTHER_BANKCARD: 原银行卡异常退到其他银行卡(发起异常退款成功后返回)
type RefundChannel int32

const (
	RefundChannel_RefundChannel_UNKNOWN RefundChannel = 0
	RefundChannel_ORIGINAL              RefundChannel = 1
	RefundChannel_BALANCE               RefundChannel = 2
	RefundChannel_OTHER_BALANCE         RefundChannel = 3
	RefundChannel_OTHER_BANKCARD        RefundChannel = 4
)

// Enum value maps for RefundChannel.
var (
	RefundChannel_name = map[int32]string{
		0: "RefundChannel_UNKNOWN",
		1: "ORIGINAL",
		2: "BALANCE",
		3: "OTHER_BALANCE",
		4: "OTHER_BANKCARD",
	}
	RefundChannel_value = map[string]int32{
		"RefundChannel_UNKNOWN": 0,
		"ORIGINAL":              1,
		"BALANCE":               2,
		"OTHER_BALANCE":         3,
		"OTHER_BANKCARD":        4,
	}
)

func (x RefundChannel) Enum() *RefundChannel {
	p := new(RefundChannel)
	*p = x
	return p
}

func (x RefundChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_refund_refund_proto_enumTypes[1].Descriptor()
}

func (RefundChannel) Type() protoreflect.EnumType {
	return &file_enum_refund_refund_proto_enumTypes[1]
}

func (x RefundChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundChannel.Descriptor instead.
func (RefundChannel) EnumDescriptor() ([]byte, []int) {
	return file_enum_refund_refund_proto_rawDescGZIP(), []int{1}
}

var File_enum_refund_refund_proto protoreflect.FileDescriptor

const file_enum_refund_refund_proto_rawDesc = "" +
	"\n" +
	"\x18enum/refund/refund.proto\x12\x06refund*u\n" +
	"\x06Status\x12\x12\n" +
	"\x0eStatus_UNKNOWN\x10\x00\x12\v\n" +
	"\aCreated\x10\x01\x12\v\n" +
	"\aPending\x10\x02\x12\v\n" +
	"\aSuccess\x10\x03\x12\n" +
	"\n" +
	"\x06Failed\x10\x04\x12\f\n" +
	"\bAbnormal\x10\x05\x12\n" +
	"\n" +
	"\x06Closed\x10\x06\x12\n" +
	"\n" +
	"\x06Cancel\x10\a*l\n" +
	"\rRefundChannel\x12\x19\n" +
	"\x15RefundChannel_UNKNOWN\x10\x00\x12\f\n" +
	"\bORIGINAL\x10\x01\x12\v\n" +
	"\aBALANCE\x10\x02\x12\x11\n" +
	"\rOTHER_BALANCE\x10\x03\x12\x12\n" +
	"\x0eOTHER_BANKCARD\x10\x04B\x0fZ\r./enum/refundb\x06proto3"

var (
	file_enum_refund_refund_proto_rawDescOnce sync.Once
	file_enum_refund_refund_proto_rawDescData []byte
)

func file_enum_refund_refund_proto_rawDescGZIP() []byte {
	file_enum_refund_refund_proto_rawDescOnce.Do(func() {
		file_enum_refund_refund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_refund_refund_proto_rawDesc), len(file_enum_refund_refund_proto_rawDesc)))
	})
	return file_enum_refund_refund_proto_rawDescData
}

var file_enum_refund_refund_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enum_refund_refund_proto_goTypes = []any{
	(Status)(0),        // 0: refund.Status
	(RefundChannel)(0), // 1: refund.RefundChannel
}
var file_enum_refund_refund_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_refund_refund_proto_init() }
func file_enum_refund_refund_proto_init() {
	if File_enum_refund_refund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_refund_refund_proto_rawDesc), len(file_enum_refund_refund_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_refund_refund_proto_goTypes,
		DependencyIndexes: file_enum_refund_refund_proto_depIdxs,
		EnumInfos:         file_enum_refund_refund_proto_enumTypes,
	}.Build()
	File_enum_refund_refund_proto = out.File
	file_enum_refund_refund_proto_goTypes = nil
	file_enum_refund_refund_proto_depIdxs = nil
}
