// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: enum/refund/refund.proto

// 定义包名

package refund

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Status_UNKNOWN Status = 0
	// 预支付,创建支付订单后的状态，等待用户完成支付
	Status_Pending Status = 1
	// 成功
	Status_Success Status = 2
	// 失败
	Status_Failed Status = 3
	// 异常
	Status_Abnormal Status = 4
	Status_Closed   Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Status_UNKNOWN",
		1: "Pending",
		2: "Success",
		3: "Failed",
		4: "Abnormal",
		5: "Closed",
	}
	Status_value = map[string]int32{
		"Status_UNKNOWN": 0,
		"Pending":        1,
		"Success":        2,
		"Failed":         3,
		"Abnormal":       4,
		"Closed":         5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_refund_refund_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_enum_refund_refund_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_enum_refund_refund_proto_rawDescGZIP(), []int{0}
}

// ORIGINAL: 原路退款
//
//BALANCE: 退回到余额
//
//OTHER_BALANCE: 原账户异常退到其他余额账户
//
//OTHER_BANKCARD: 原银行卡异常退到其他银行卡(发起异常退款成功后返回)
type RefundChannel int32

const (
	RefundChannel_RefundChannel_UNKNOWN RefundChannel = 0
	RefundChannel_ORIGINAL              RefundChannel = 1
	RefundChannel_BALANCE               RefundChannel = 2
	RefundChannel_OTHER_BALANCE         RefundChannel = 3
	RefundChannel_OTHER_BANKCARD        RefundChannel = 4
)

// Enum value maps for RefundChannel.
var (
	RefundChannel_name = map[int32]string{
		0: "RefundChannel_UNKNOWN",
		1: "ORIGINAL",
		2: "BALANCE",
		3: "OTHER_BALANCE",
		4: "OTHER_BANKCARD",
	}
	RefundChannel_value = map[string]int32{
		"RefundChannel_UNKNOWN": 0,
		"ORIGINAL":              1,
		"BALANCE":               2,
		"OTHER_BALANCE":         3,
		"OTHER_BANKCARD":        4,
	}
)

func (x RefundChannel) Enum() *RefundChannel {
	p := new(RefundChannel)
	*p = x
	return p
}

func (x RefundChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_refund_refund_proto_enumTypes[1].Descriptor()
}

func (RefundChannel) Type() protoreflect.EnumType {
	return &file_enum_refund_refund_proto_enumTypes[1]
}

func (x RefundChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundChannel.Descriptor instead.
func (RefundChannel) EnumDescriptor() ([]byte, []int) {
	return file_enum_refund_refund_proto_rawDescGZIP(), []int{1}
}

var File_enum_refund_refund_proto protoreflect.FileDescriptor

var file_enum_refund_refund_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x2f, 0x72, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x2a, 0x5c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x10, 0x05,
	0x2a, 0x6c, 0x0a, 0x0d, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x4f, 0x52, 0x49, 0x47, 0x49, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x41,
	0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x54, 0x48, 0x45, 0x52,
	0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x54,
	0x48, 0x45, 0x52, 0x5f, 0x42, 0x41, 0x4e, 0x4b, 0x43, 0x41, 0x52, 0x44, 0x10, 0x04, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_refund_refund_proto_rawDescOnce sync.Once
	file_enum_refund_refund_proto_rawDescData = file_enum_refund_refund_proto_rawDesc
)

func file_enum_refund_refund_proto_rawDescGZIP() []byte {
	file_enum_refund_refund_proto_rawDescOnce.Do(func() {
		file_enum_refund_refund_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_refund_refund_proto_rawDescData)
	})
	return file_enum_refund_refund_proto_rawDescData
}

var file_enum_refund_refund_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enum_refund_refund_proto_goTypes = []interface{}{
	(Status)(0),        // 0: refund.Status
	(RefundChannel)(0), // 1: refund.RefundChannel
}
var file_enum_refund_refund_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_refund_refund_proto_init() }
func file_enum_refund_refund_proto_init() {
	if File_enum_refund_refund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_refund_refund_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_refund_refund_proto_goTypes,
		DependencyIndexes: file_enum_refund_refund_proto_depIdxs,
		EnumInfos:         file_enum_refund_refund_proto_enumTypes,
	}.Build()
	File_enum_refund_refund_proto = out.File
	file_enum_refund_refund_proto_rawDesc = nil
	file_enum_refund_refund_proto_goTypes = nil
	file_enum_refund_refund_proto_depIdxs = nil
}
