// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: enum/action/action.proto

// 定义包名

package action

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	//Redirect | Qrcode | Prepay
	Action_Action_UNKNOWN Action = 0
	Action_Redirect       Action = 1
	Action_Qrcode         Action = 2
	Action_Prepay         Action = 3
	// 无回调的跳转支付，拉卡拉私有协议版
	Action_RedirectNOBack Action = 4
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "Action_UNKNOWN",
		1: "Redirect",
		2: "Qrcode",
		3: "Prepay",
		4: "RedirectNOBack",
	}
	Action_value = map[string]int32{
		"Action_UNKNOWN": 0,
		"Redirect":       1,
		"Qrcode":         2,
		"Prepay":         3,
		"RedirectNOBack": 4,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_action_action_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_enum_action_action_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_enum_action_action_proto_rawDescGZIP(), []int{0}
}

var File_enum_action_action_proto protoreflect.FileDescriptor

var file_enum_action_action_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2a, 0x56, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x0e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x79, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x4e, 0x4f, 0x42, 0x61, 0x63, 0x6b, 0x10, 0x04, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f,
	0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_enum_action_action_proto_rawDescOnce sync.Once
	file_enum_action_action_proto_rawDescData = file_enum_action_action_proto_rawDesc
)

func file_enum_action_action_proto_rawDescGZIP() []byte {
	file_enum_action_action_proto_rawDescOnce.Do(func() {
		file_enum_action_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_action_action_proto_rawDescData)
	})
	return file_enum_action_action_proto_rawDescData
}

var file_enum_action_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_action_action_proto_goTypes = []interface{}{
	(Action)(0), // 0: action.Action
}
var file_enum_action_action_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_action_action_proto_init() }
func file_enum_action_action_proto_init() {
	if File_enum_action_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_action_action_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_action_action_proto_goTypes,
		DependencyIndexes: file_enum_action_action_proto_depIdxs,
		EnumInfos:         file_enum_action_action_proto_enumTypes,
	}.Build()
	File_enum_action_action_proto = out.File
	file_enum_action_action_proto_rawDesc = nil
	file_enum_action_action_proto_goTypes = nil
	file_enum_action_action_proto_depIdxs = nil
}
