// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: enum/event.proto

// 定义包名

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event int32

const (
	Event_Event_UNKNOWN Event = 0
	// 支付
	Event_PAYMENT Event = 1
	// 退款
	Event_REFUND Event = 2
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "Event_UNKNOWN",
		1: "PAYMENT",
		2: "REFUND",
	}
	Event_value = map[string]int32{
		"Event_UNKNOWN": 0,
		"PAYMENT":       1,
		"REFUND":        2,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_event_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_enum_event_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_enum_event_proto_rawDescGZIP(), []int{0}
}

var File_enum_event_proto protoreflect.FileDescriptor

const file_enum_event_proto_rawDesc = "" +
	"\n" +
	"\x10enum/event.proto\x12\x04enum*3\n" +
	"\x05Event\x12\x11\n" +
	"\rEvent_UNKNOWN\x10\x00\x12\v\n" +
	"\aPAYMENT\x10\x01\x12\n" +
	"\n" +
	"\x06REFUND\x10\x02B\bZ\x06./enumb\x06proto3"

var (
	file_enum_event_proto_rawDescOnce sync.Once
	file_enum_event_proto_rawDescData []byte
)

func file_enum_event_proto_rawDescGZIP() []byte {
	file_enum_event_proto_rawDescOnce.Do(func() {
		file_enum_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_event_proto_rawDesc), len(file_enum_event_proto_rawDesc)))
	})
	return file_enum_event_proto_rawDescData
}

var file_enum_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_event_proto_goTypes = []any{
	(Event)(0), // 0: enum.Event
}
var file_enum_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_event_proto_init() }
func file_enum_event_proto_init() {
	if File_enum_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_event_proto_rawDesc), len(file_enum_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_event_proto_goTypes,
		DependencyIndexes: file_enum_event_proto_depIdxs,
		EnumInfos:         file_enum_event_proto_enumTypes,
	}.Build()
	File_enum_event_proto = out.File
	file_enum_event_proto_goTypes = nil
	file_enum_event_proto_depIdxs = nil
}
