package enum

const (
	JSAPI = "JSAPI_PAY"
	// QUICK_WAP_WAY
	QUICK_WAP_WAY = "QUICK_WAP_WAY"
	APP_WAY       = "alipay.trade.app.pay"
	// FACE_TO_FACE_PAYMENT
	FACE_TO_FACE_PAYMENT = "FACE_TO_FACE_PAYMENT"
	QR_CODE_OFFLINE      = "QR_CODE_OFFLINE"
)
