// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: enum/order_share/share.proto

// 定义包名

package order_share

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN    Status = 0
	Status_PROCESSING Status = 1
	Status_FINISHED   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PROCESSING",
		2: "FINISHED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":    0,
		"PROCESSING": 1,
		"FINISHED":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_order_share_share_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_enum_order_share_share_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_enum_order_share_share_proto_rawDescGZIP(), []int{0}
}

type ShareOrderStaus int32

const (
	ShareOrderStaus_SHARE_ORDER_UNKNOWN    ShareOrderStaus = 0
	ShareOrderStaus_SHARE_ORDER_PROCESSING ShareOrderStaus = 1
	ShareOrderStaus_SHARE_ORDER_SUCCESS    ShareOrderStaus = 2
	ShareOrderStaus_SHARE_ORDER_FAILED     ShareOrderStaus = 3
)

// Enum value maps for ShareOrderStaus.
var (
	ShareOrderStaus_name = map[int32]string{
		0: "SHARE_ORDER_UNKNOWN",
		1: "SHARE_ORDER_PROCESSING",
		2: "SHARE_ORDER_SUCCESS",
		3: "SHARE_ORDER_FAILED",
	}
	ShareOrderStaus_value = map[string]int32{
		"SHARE_ORDER_UNKNOWN":    0,
		"SHARE_ORDER_PROCESSING": 1,
		"SHARE_ORDER_SUCCESS":    2,
		"SHARE_ORDER_FAILED":     3,
	}
)

func (x ShareOrderStaus) Enum() *ShareOrderStaus {
	p := new(ShareOrderStaus)
	*p = x
	return p
}

func (x ShareOrderStaus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShareOrderStaus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_order_share_share_proto_enumTypes[1].Descriptor()
}

func (ShareOrderStaus) Type() protoreflect.EnumType {
	return &file_enum_order_share_share_proto_enumTypes[1]
}

func (x ShareOrderStaus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShareOrderStaus.Descriptor instead.
func (ShareOrderStaus) EnumDescriptor() ([]byte, []int) {
	return file_enum_order_share_share_proto_rawDescGZIP(), []int{1}
}

var File_enum_order_share_share_proto protoreflect.FileDescriptor

var file_enum_order_share_share_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2a, 0x33, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x02,
	0x2a, 0x77, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x48, 0x41, 0x52, 0x45, 0x5f, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16,
	0x53, 0x48, 0x41, 0x52, 0x45, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x43,
	0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x48, 0x41, 0x52,
	0x45, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x02, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x48, 0x41, 0x52, 0x45, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_order_share_share_proto_rawDescOnce sync.Once
	file_enum_order_share_share_proto_rawDescData = file_enum_order_share_share_proto_rawDesc
)

func file_enum_order_share_share_proto_rawDescGZIP() []byte {
	file_enum_order_share_share_proto_rawDescOnce.Do(func() {
		file_enum_order_share_share_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_order_share_share_proto_rawDescData)
	})
	return file_enum_order_share_share_proto_rawDescData
}

var file_enum_order_share_share_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enum_order_share_share_proto_goTypes = []interface{}{
	(Status)(0),          // 0: order_share.Status
	(ShareOrderStaus)(0), // 1: order_share.ShareOrderStaus
}
var file_enum_order_share_share_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_order_share_share_proto_init() }
func file_enum_order_share_share_proto_init() {
	if File_enum_order_share_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_order_share_share_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_order_share_share_proto_goTypes,
		DependencyIndexes: file_enum_order_share_share_proto_depIdxs,
		EnumInfos:         file_enum_order_share_share_proto_enumTypes,
	}.Build()
	File_enum_order_share_share_proto = out.File
	file_enum_order_share_share_proto_rawDesc = nil
	file_enum_order_share_share_proto_goTypes = nil
	file_enum_order_share_share_proto_depIdxs = nil
}
