// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: enum/order_share/share.proto

// 定义包名

package order_share

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN    Status = 0
	Status_PROCESSING Status = 1
	Status_FINISHED   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PROCESSING",
		2: "FINISHED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":    0,
		"PROCESSING": 1,
		"FINISHED":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_order_share_share_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_enum_order_share_share_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_enum_order_share_share_proto_rawDescGZIP(), []int{0}
}

type ShareOrderStaus int32

const (
	ShareOrderStaus_SHARE_ORDER_UNKNOWN    ShareOrderStaus = 0
	ShareOrderStaus_SHARE_ORDER_PROCESSING ShareOrderStaus = 1
	ShareOrderStaus_SHARE_ORDER_SUCCESS    ShareOrderStaus = 2
	ShareOrderStaus_SHARE_ORDER_FAILED     ShareOrderStaus = 3
)

// Enum value maps for ShareOrderStaus.
var (
	ShareOrderStaus_name = map[int32]string{
		0: "SHARE_ORDER_UNKNOWN",
		1: "SHARE_ORDER_PROCESSING",
		2: "SHARE_ORDER_SUCCESS",
		3: "SHARE_ORDER_FAILED",
	}
	ShareOrderStaus_value = map[string]int32{
		"SHARE_ORDER_UNKNOWN":    0,
		"SHARE_ORDER_PROCESSING": 1,
		"SHARE_ORDER_SUCCESS":    2,
		"SHARE_ORDER_FAILED":     3,
	}
)

func (x ShareOrderStaus) Enum() *ShareOrderStaus {
	p := new(ShareOrderStaus)
	*p = x
	return p
}

func (x ShareOrderStaus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShareOrderStaus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_order_share_share_proto_enumTypes[1].Descriptor()
}

func (ShareOrderStaus) Type() protoreflect.EnumType {
	return &file_enum_order_share_share_proto_enumTypes[1]
}

func (x ShareOrderStaus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShareOrderStaus.Descriptor instead.
func (ShareOrderStaus) EnumDescriptor() ([]byte, []int) {
	return file_enum_order_share_share_proto_rawDescGZIP(), []int{1}
}

var File_enum_order_share_share_proto protoreflect.FileDescriptor

const file_enum_order_share_share_proto_rawDesc = "" +
	"\n" +
	"\x1cenum/order_share/share.proto\x12\vorder_share*3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02*w\n" +
	"\x0fShareOrderStaus\x12\x17\n" +
	"\x13SHARE_ORDER_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SHARE_ORDER_PROCESSING\x10\x01\x12\x17\n" +
	"\x13SHARE_ORDER_SUCCESS\x10\x02\x12\x16\n" +
	"\x12SHARE_ORDER_FAILED\x10\x03B\x14Z\x12./enum/order_shareb\x06proto3"

var (
	file_enum_order_share_share_proto_rawDescOnce sync.Once
	file_enum_order_share_share_proto_rawDescData []byte
)

func file_enum_order_share_share_proto_rawDescGZIP() []byte {
	file_enum_order_share_share_proto_rawDescOnce.Do(func() {
		file_enum_order_share_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_order_share_share_proto_rawDesc), len(file_enum_order_share_share_proto_rawDesc)))
	})
	return file_enum_order_share_share_proto_rawDescData
}

var file_enum_order_share_share_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enum_order_share_share_proto_goTypes = []any{
	(Status)(0),          // 0: order_share.Status
	(ShareOrderStaus)(0), // 1: order_share.ShareOrderStaus
}
var file_enum_order_share_share_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_order_share_share_proto_init() }
func file_enum_order_share_share_proto_init() {
	if File_enum_order_share_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_order_share_share_proto_rawDesc), len(file_enum_order_share_share_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_order_share_share_proto_goTypes,
		DependencyIndexes: file_enum_order_share_share_proto_depIdxs,
		EnumInfos:         file_enum_order_share_share_proto_enumTypes,
	}.Build()
	File_enum_order_share_share_proto = out.File
	file_enum_order_share_share_proto_goTypes = nil
	file_enum_order_share_share_proto_depIdxs = nil
}
