// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: enum/transfer/transfer.proto

// 定义包名

package transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// // ACCEPTED:  转账已受理，可原单重试（非终态）。
////
//// PROCESSING:  转账锁定资金中。如果一直停留在该状态，建议检查账户余额是否足够，如余额不足，可充值后再原单重试（非终态）。
////
//// WAIT_USER_CONFIRM:  待收款用户确认，当前转账单据资金已锁定，可拉起微信收款确认页面进行收款确认（非终态）。
////
//// TRANSFERING:  转账中，可拉起微信收款确认页面再次重试确认收款（非终态）。
////
//// FINISHED:  转账成功，表示转账单据已成功（终态）。
////
//// FAIL:  转账失败，表示该笔转账单据已失败。若需重新向用户转账，请重新生成单据并再次发起（终态）。
////
//// CANCELING:  转账撤销中，商户撤销请求受理成功，该笔转账正在撤销中，需查单确认撤销的转账单据状态（非终态）。
////
//// CANCELLED:  转账撤销完成，代表转账单据已撤销成功（终态）。
type TransferStatus int32

const (
	TransferStatus_TransferStatus_UNKNOWN           TransferStatus = 0
	TransferStatus_TransferStatus_ACCEPTED          TransferStatus = 1
	TransferStatus_TransferStatus_PROCESSING        TransferStatus = 2
	TransferStatus_TransferStatus_WAIT_PAY          TransferStatus = 3
	TransferStatus_TransferStatus_FINISHED          TransferStatus = 4
	TransferStatus_TransferStatus_CLOSE             TransferStatus = 5
	TransferStatus_TransferStatus_CANCELED          TransferStatus = 6
	TransferStatus_TransferStatus_FAILED            TransferStatus = 7
	TransferStatus_TransferStatus_CANCELING         TransferStatus = 8
	TransferStatus_TransferStatus_TRANSFERING       TransferStatus = 9
	TransferStatus_TransferStatus_WAIT_USER_CONFIRM TransferStatus = 10 //TransferStatus_SUCCESS = 11;
)

// Enum value maps for TransferStatus.
var (
	TransferStatus_name = map[int32]string{
		0:  "TransferStatus_UNKNOWN",
		1:  "TransferStatus_ACCEPTED",
		2:  "TransferStatus_PROCESSING",
		3:  "TransferStatus_WAIT_PAY",
		4:  "TransferStatus_FINISHED",
		5:  "TransferStatus_CLOSE",
		6:  "TransferStatus_CANCELED",
		7:  "TransferStatus_FAILED",
		8:  "TransferStatus_CANCELING",
		9:  "TransferStatus_TRANSFERING",
		10: "TransferStatus_WAIT_USER_CONFIRM",
	}
	TransferStatus_value = map[string]int32{
		"TransferStatus_UNKNOWN":           0,
		"TransferStatus_ACCEPTED":          1,
		"TransferStatus_PROCESSING":        2,
		"TransferStatus_WAIT_PAY":          3,
		"TransferStatus_FINISHED":          4,
		"TransferStatus_CLOSE":             5,
		"TransferStatus_CANCELED":          6,
		"TransferStatus_FAILED":            7,
		"TransferStatus_CANCELING":         8,
		"TransferStatus_TRANSFERING":       9,
		"TransferStatus_WAIT_USER_CONFIRM": 10,
	}
)

func (x TransferStatus) Enum() *TransferStatus {
	p := new(TransferStatus)
	*p = x
	return p
}

func (x TransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_transfer_transfer_proto_enumTypes[0].Descriptor()
}

func (TransferStatus) Type() protoreflect.EnumType {
	return &file_enum_transfer_transfer_proto_enumTypes[0]
}

func (x TransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatus.Descriptor instead.
func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_transfer_transfer_proto_rawDescGZIP(), []int{0}
}

type UnitTransferStatus int32

const (
	UnitTransferStatus_UnitTransferStatus_UNKNOWN           UnitTransferStatus = 0
	UnitTransferStatus_UnitTransferStatus_ACCEPTED          UnitTransferStatus = 1
	UnitTransferStatus_UnitTransferStatus_PROCESSING        UnitTransferStatus = 2
	UnitTransferStatus_UnitTransferStatus_WAIT_PAY          UnitTransferStatus = 3
	UnitTransferStatus_UnitTransferStatus_FINISHED          UnitTransferStatus = 4
	UnitTransferStatus_UnitTransferStatus_CLOSE             UnitTransferStatus = 5
	UnitTransferStatus_UnitTransferStatus_CANCELED          UnitTransferStatus = 6
	UnitTransferStatus_UnitTransferStatus_FAILED            UnitTransferStatus = 7
	UnitTransferStatus_UnitTransferStatus_CANCELING         UnitTransferStatus = 8
	UnitTransferStatus_UnitTransferStatus_TRANSFERING       UnitTransferStatus = 9
	UnitTransferStatus_UnitTransferStatus_WAIT_USER_CONFIRM UnitTransferStatus = 10
	UnitTransferStatus_UnitTransferStatus_SUCCESS           UnitTransferStatus = 11
)

// Enum value maps for UnitTransferStatus.
var (
	UnitTransferStatus_name = map[int32]string{
		0:  "UnitTransferStatus_UNKNOWN",
		1:  "UnitTransferStatus_ACCEPTED",
		2:  "UnitTransferStatus_PROCESSING",
		3:  "UnitTransferStatus_WAIT_PAY",
		4:  "UnitTransferStatus_FINISHED",
		5:  "UnitTransferStatus_CLOSE",
		6:  "UnitTransferStatus_CANCELED",
		7:  "UnitTransferStatus_FAILED",
		8:  "UnitTransferStatus_CANCELING",
		9:  "UnitTransferStatus_TRANSFERING",
		10: "UnitTransferStatus_WAIT_USER_CONFIRM",
		11: "UnitTransferStatus_SUCCESS",
	}
	UnitTransferStatus_value = map[string]int32{
		"UnitTransferStatus_UNKNOWN":           0,
		"UnitTransferStatus_ACCEPTED":          1,
		"UnitTransferStatus_PROCESSING":        2,
		"UnitTransferStatus_WAIT_PAY":          3,
		"UnitTransferStatus_FINISHED":          4,
		"UnitTransferStatus_CLOSE":             5,
		"UnitTransferStatus_CANCELED":          6,
		"UnitTransferStatus_FAILED":            7,
		"UnitTransferStatus_CANCELING":         8,
		"UnitTransferStatus_TRANSFERING":       9,
		"UnitTransferStatus_WAIT_USER_CONFIRM": 10,
		"UnitTransferStatus_SUCCESS":           11,
	}
)

func (x UnitTransferStatus) Enum() *UnitTransferStatus {
	p := new(UnitTransferStatus)
	*p = x
	return p
}

func (x UnitTransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitTransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_transfer_transfer_proto_enumTypes[1].Descriptor()
}

func (UnitTransferStatus) Type() protoreflect.EnumType {
	return &file_enum_transfer_transfer_proto_enumTypes[1]
}

func (x UnitTransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitTransferStatus.Descriptor instead.
func (UnitTransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_transfer_transfer_proto_rawDescGZIP(), []int{1}
}

type DetailStatus int32

const (
	DetailStatus_DetailStatus_UNKNOWN    DetailStatus = 0
	DetailStatus_DetailStatus_WAITING    DetailStatus = 1
	DetailStatus_DetailStatus_PROCESSING DetailStatus = 2
	DetailStatus_DetailStatus_SUCCESS    DetailStatus = 3
	DetailStatus_DetailStatus_FAILED     DetailStatus = 4
)

// Enum value maps for DetailStatus.
var (
	DetailStatus_name = map[int32]string{
		0: "DetailStatus_UNKNOWN",
		1: "DetailStatus_WAITING",
		2: "DetailStatus_PROCESSING",
		3: "DetailStatus_SUCCESS",
		4: "DetailStatus_FAILED",
	}
	DetailStatus_value = map[string]int32{
		"DetailStatus_UNKNOWN":    0,
		"DetailStatus_WAITING":    1,
		"DetailStatus_PROCESSING": 2,
		"DetailStatus_SUCCESS":    3,
		"DetailStatus_FAILED":     4,
	}
)

func (x DetailStatus) Enum() *DetailStatus {
	p := new(DetailStatus)
	*p = x
	return p
}

func (x DetailStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetailStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_transfer_transfer_proto_enumTypes[2].Descriptor()
}

func (DetailStatus) Type() protoreflect.EnumType {
	return &file_enum_transfer_transfer_proto_enumTypes[2]
}

func (x DetailStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetailStatus.Descriptor instead.
func (DetailStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_transfer_transfer_proto_rawDescGZIP(), []int{2}
}

var File_enum_transfer_transfer_proto protoreflect.FileDescriptor

const file_enum_transfer_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1cenum/transfer/transfer.proto\x12\btransfer*\xd8\x02\n" +
	"\x0eTransferStatus\x12\x1a\n" +
	"\x16TransferStatus_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17TransferStatus_ACCEPTED\x10\x01\x12\x1d\n" +
	"\x19TransferStatus_PROCESSING\x10\x02\x12\x1b\n" +
	"\x17TransferStatus_WAIT_PAY\x10\x03\x12\x1b\n" +
	"\x17TransferStatus_FINISHED\x10\x04\x12\x18\n" +
	"\x14TransferStatus_CLOSE\x10\x05\x12\x1b\n" +
	"\x17TransferStatus_CANCELED\x10\x06\x12\x19\n" +
	"\x15TransferStatus_FAILED\x10\a\x12\x1c\n" +
	"\x18TransferStatus_CANCELING\x10\b\x12\x1e\n" +
	"\x1aTransferStatus_TRANSFERING\x10\t\x12$\n" +
	" TransferStatus_WAIT_USER_CONFIRM\x10\n" +
	"*\xa8\x03\n" +
	"\x12UnitTransferStatus\x12\x1e\n" +
	"\x1aUnitTransferStatus_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bUnitTransferStatus_ACCEPTED\x10\x01\x12!\n" +
	"\x1dUnitTransferStatus_PROCESSING\x10\x02\x12\x1f\n" +
	"\x1bUnitTransferStatus_WAIT_PAY\x10\x03\x12\x1f\n" +
	"\x1bUnitTransferStatus_FINISHED\x10\x04\x12\x1c\n" +
	"\x18UnitTransferStatus_CLOSE\x10\x05\x12\x1f\n" +
	"\x1bUnitTransferStatus_CANCELED\x10\x06\x12\x1d\n" +
	"\x19UnitTransferStatus_FAILED\x10\a\x12 \n" +
	"\x1cUnitTransferStatus_CANCELING\x10\b\x12\"\n" +
	"\x1eUnitTransferStatus_TRANSFERING\x10\t\x12(\n" +
	"$UnitTransferStatus_WAIT_USER_CONFIRM\x10\n" +
	"\x12\x1e\n" +
	"\x1aUnitTransferStatus_SUCCESS\x10\v*\x92\x01\n" +
	"\fDetailStatus\x12\x18\n" +
	"\x14DetailStatus_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14DetailStatus_WAITING\x10\x01\x12\x1b\n" +
	"\x17DetailStatus_PROCESSING\x10\x02\x12\x18\n" +
	"\x14DetailStatus_SUCCESS\x10\x03\x12\x17\n" +
	"\x13DetailStatus_FAILED\x10\x04B\x11Z\x0f./enum/transferb\x06proto3"

var (
	file_enum_transfer_transfer_proto_rawDescOnce sync.Once
	file_enum_transfer_transfer_proto_rawDescData []byte
)

func file_enum_transfer_transfer_proto_rawDescGZIP() []byte {
	file_enum_transfer_transfer_proto_rawDescOnce.Do(func() {
		file_enum_transfer_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_transfer_transfer_proto_rawDesc), len(file_enum_transfer_transfer_proto_rawDesc)))
	})
	return file_enum_transfer_transfer_proto_rawDescData
}

var file_enum_transfer_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_enum_transfer_transfer_proto_goTypes = []any{
	(TransferStatus)(0),     // 0: transfer.TransferStatus
	(UnitTransferStatus)(0), // 1: transfer.UnitTransferStatus
	(DetailStatus)(0),       // 2: transfer.DetailStatus
}
var file_enum_transfer_transfer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_transfer_transfer_proto_init() }
func file_enum_transfer_transfer_proto_init() {
	if File_enum_transfer_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_transfer_transfer_proto_rawDesc), len(file_enum_transfer_transfer_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_transfer_transfer_proto_goTypes,
		DependencyIndexes: file_enum_transfer_transfer_proto_depIdxs,
		EnumInfos:         file_enum_transfer_transfer_proto_enumTypes,
	}.Build()
	File_enum_transfer_transfer_proto = out.File
	file_enum_transfer_transfer_proto_goTypes = nil
	file_enum_transfer_transfer_proto_depIdxs = nil
}
